//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSESAPI.DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class batch_closing_master
    {
        public int id { get; set; }
        public string kiosk_id { get; set; }
        public System.DateTime batchclosedatetime { get; set; }
        public int reportbatchno { get; set; }
        public int start_rcptno { get; set; }
        public int end_rcptno { get; set; }
        public int cash_rcpts { get; set; }
        public decimal cash_amnt { get; set; }
        public int chq_rcpts { get; set; }
        public decimal chq_amnt { get; set; }
        public int card_rcpts { get; set; }
        public decimal card_amnt { get; set; }
        public int ttl_rcpts { get; set; }
        public decimal ttl_amnt { get; set; }
        public string token_id { get; set; }
    }
}
