//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSESAPI.DataLayer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BSESEntities : DbContext
    {
        public BSESEntities()
            : base("name=BSESEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<batch_closing_master> batch_closing_master { get; set; }
        public virtual DbSet<kiosk_attendance> kiosk_attendance { get; set; }
        public virtual DbSet<TransactionsDB> TransactionsDBs { get; set; }
    }
}
