//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSESAPI.DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kiosk_attendance
    {
        public int id { get; set; }
        public string kiosk_id { get; set; }
        public Nullable<System.DateTime> login_date_time { get; set; }
        public Nullable<System.DateTime> log_out_time { get; set; }
        public string atpm_mchn_ip { get; set; }
        public System.DateTime inserted_date { get; set; }
        public string inserted_by { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string status { get; set; }
        public string tokenId { get; set; }
    }
}
